# Generated by Django 2.1.15 on 2020-11-11 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consecutivo', models.IntegerField()),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('neto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('relacion', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=30)),
                ('estado', models.CharField(default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentosDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('dir', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cell', models.CharField(blank=True, max_length=50)),
                ('resolucion', models.CharField(blank=True, max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('nit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fpago', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('existencia', models.IntegerField()),
                ('fecha', models.DateField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Medidas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unidad', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=100, unique=True)),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.Grupos')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.Medidas')),
            ],
        ),
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('celular', models.IntegerField(blank=True)),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoContribuyente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumentoTerceros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTercero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='tercero',
            name='tipocontribuyente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.TipoContribuyente'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='tipodocumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.TipoDocumentoTerceros'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='tipotercero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.TipoTercero'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='codproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.Producto'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='numfac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.Documentos'),
        ),
        migrations.AddField(
            model_name='documentosdetalle',
            name='codproduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.Producto'),
        ),
        migrations.AddField(
            model_name='documentosdetalle',
            name='numfac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.Documentos'),
        ),
        migrations.AddField(
            model_name='documentos',
            name='fpago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.FormaPago'),
        ),
        migrations.AddField(
            model_name='documentos',
            name='tercero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.Tercero'),
        ),
        migrations.AddField(
            model_name='documentos',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.TipoDocumento'),
        ),
    ]
