# Generated by Django 2.1.15 on 2020-11-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
